version: '3.8'

services:
  postgres:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - adme-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - adme-network
volumes:
  postgres_data:
  redis_data:
networks:
  adme-network:
    driver: bridge
