[project]
name = "event-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "langgraph>=0.6.5",
    "pika>=1.3.2",
]
